### PR TITLE
feat: adding database, #4

### PR DESCRIPTION
**Pull request by lubegasimon**
I have so many challenges concerning this PR, but I want to  first be able to view data in postman and pgAdminIII, then I'll not  find it so daunting to deal with the rest

for a clear picture, you can conveniently clone and run `npm install ` and try the building and some other experiments

### CODE REVIEW

**Comment by epicallan** [comment]
You should git ignore files in the dist folder and remove them from git history.

**Comment by epicallan** [comment]
The app doesn't build, I ran npm run build and it failed.

**Comment by lubegasimon** [comment]
> The app doesn't build, I ran npm run build and it failed.

yea, it throws some weird errors, I tried resolving them, but all in vain

**Comment by epicallan** [comment]
Try to simplify and trim down the app and get it to a point that builds and runs. After that add one feature at a time which we can review in separate PRs

**Comment by lubegasimon** [comment]
> Try to simplify and trim down the app and get it to a point that builds and runs. After that add one feature at a time which we can review in separate PRs

@epicallan, before I got started with setting up the database, the app was building, so it's failure to build has something to do with database set-up..

**Comment by lubegasimon** [comment]
> The app doesn't build, I ran npm run build and it failed.

@epicallan , it's resolved

**Comment by epicallan** [comment]
> @epicallan, it's resolved.

The branch issue-4-adding-database still doesn't build after updating it. BTW add Travis CI

**Comment by lubegasimon** [comment]
> > @epicallan, it's resolved.
> 
> The branch issue-4-adding-database still doesn't build after updating it. BTW add Travis CI

it seems am missing some concept and I can't figure out what it is....

**Comment by epicallan** [comment]
Can you then close this PR and open up another one where you have the project structure fleshed out with a simple hello world like route working. Thereafter you open up small PRs with one small feature at a time.

**Comment by lubegasimon** [comment]
> Can you then close this PR and open up another one where you have the project structure fleshed out with a simple hello world like route working or whichever routes you have set up already. Thereafter you open up small PRs with one small feature at a time.

**Pull request closed without merging**
